export const films = [...new Array(10)].map(() => {
  return {
    title: [
      `The favourite`,
      `Roma`,
      `Green book`,
      `Black panther`,
      `BlacKkKlansman`,
      `Bohemian rhapsody`,
      `Vice`,
      `At eternity’s gate`,
      `The wife`,
      `Can you ever forgive me?`,
      `If Beale Street could talk`,
      `Cold war`,
      `Incredibles 2`,
      `Isle of dogs`,
      `Ralph breaks the internet`,
      `Spider-Man: into the Spider-Verse`,
    ][Math.floor(Math.random() * 16)],
    poster: [
      `accused`,
      `blackmail`,
      `blue-blazes`,
      `fuga-da-new-york`,
      `moonrise`,
      `three-friends`,
    ][Math.floor(Math.random() * 6)],
    description: [
      `Lorem ipsum dolor sit amet, consectetur adipiscing elit.`,
      `Cras aliquet varius magna, non porta ligula feugiat eget.`,
      `Fusce tristique felis at fermentum pharetra.`,
      `Aliquam id orci ut lectus varius viverra.`,
      `Nullam nunc ex, convallis sed finibus eget, sollicitudin eget ante.`,
      `Phasellus eros mauris, condimentum sed nibh vitae, sodales efficitur ipsum.`,
      `Sed blandit, eros vel aliquam faucibus, purus ex euismod diam, eu luctus nunc ante ut dui.`,
      `Sed sed nisi sed augue convallis suscipit in sed felis.`,
      `Aliquam erat volutpat.`,
      `Nunc fermentum tortor ac porta dapibus.`,
      `In rutrum ac purus sit amet tempus.`,
    ],
    rating: (Math.random() * (10 - 1) + 1).toFixed(1),
    year: Math.floor(Math.random() * (2019 - 2000) + 2000),
    genre: new Set([
      `Comedy`,
      `Horror`,
      `Drama`,
      `Fantasy`,
      `Thriller`,
      `Animation`,
    ]),
    comments: Math.round(Math.random() * 100),
    duration: `1h${Math.floor(Math.random() * (60 - 1) + 1)}m`,
  };
});
